### ISSUE TITLE
Output `0.000009` instead of `9.00E-06` in invoicing and write cost with 2 decimal points

### ISSUE THREAD

**Issue by knikolla** [nerc-project/coldfront-plugin-cloud#157]
https://github.com/CCI-MOC/process_csv_report/issues/35

**Comment by QuanMPhm** [comment]
@knikolla Just so I'm sure, you want me to modify [`calculate_storage_gb_hours.py`](https://github.com/nerc-project/coldfront-plugin-cloud/blob/main/src/coldfront_plugin_cloud/management/commands/calculate_storage_gb_hours.py), or the functions it calls, so that in the invoice it exports, the rate for Storage GB Hours will be `0.000009`, and the cost row will have 2 decimal points?

Why do we worry about rounding here if we will round it elsewhere, like in your [PR](https://github.com/CCI-MOC/process_csv_report/pull/36) for the processing program?

**Comment by knikolla** [comment]
@QuanMPhm Yes. That is, the formatting when printing the CSV file for that value should not be expressed as 9 * 10^-6. 

We worry about rounding here for consistency so that the numbers between this invoice and the final processed invoice match.
